//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _235092_1305101H63074 {
            get {
                object obj = ResourceManager.GetObject("235092-1305101H63074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3271c3944d5e8985fb17e247c7854f8120b0824643c8c_xaAT1b_fw658 {
            get {
                object obj = ResourceManager.GetObject("3271c3944d5e8985fb17e247c7854f8120b0824643c8c-xaAT1b_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4fa108275f7edb23f1d653f38040128c10a46b84c9a2_lU8ntN_fw658 {
            get {
                object obj = ResourceManager.GetObject("4fa108275f7edb23f1d653f38040128c10a46b84c9a2-lU8ntN_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _552e62a7eeb0d90293bf388921105e010713ea322d542_g5db7p_fw658 {
            get {
                object obj = ResourceManager.GetObject("552e62a7eeb0d90293bf388921105e010713ea322d542-g5db7p_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5c129d16b33635427cfe1584d27731d4660ac28a49ff_OR46A1_fw658 {
            get {
                object obj = ResourceManager.GetObject("5c129d16b33635427cfe1584d27731d4660ac28a49ff-OR46A1_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _7da5cbccff20fef9e99a01c3ceffa979dbe42b164a32_vssdUf_fw658 {
            get {
                object obj = ResourceManager.GetObject("7da5cbccff20fef9e99a01c3ceffa979dbe42b164a32-vssdUf_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap c548500a485c1634f290678a75957e092c61fc6410697_W4y65v_fw658 {
            get {
                object obj = ResourceManager.GetObject("c548500a485c1634f290678a75957e092c61fc6410697-W4y65v_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cc7295d2fd8455667b814a930b1aaf8f {
            get {
                object obj = ResourceManager.GetObject("cc7295d2fd8455667b814a930b1aaf8f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap d5c3c846ea2f6eda6fffda3ddb8ac3dabe61f69948ca_2uuwwL_fw658 {
            get {
                object obj = ResourceManager.GetObject("d5c3c846ea2f6eda6fffda3ddb8ac3dabe61f69948ca-2uuwwL_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap e3e190b33a20d8c2e858e8b3874dd4e1d0097d3522398_kDKl1A_fw658 {
            get {
                object obj = ResourceManager.GetObject("e3e190b33a20d8c2e858e8b3874dd4e1d0097d3522398-kDKl1A_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ebffab0bd6177411bf1121d4649cc633353e2acc1715c_6cmlfD_fw658 {
            get {
                object obj = ResourceManager.GetObject("ebffab0bd6177411bf1121d4649cc633353e2acc1715c-6cmlfD_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f15442baa65ef623dcbc3c6cf062203a94ef8404906d_7kYBGE_fw658 {
            get {
                object obj = ResourceManager.GetObject("f15442baa65ef623dcbc3c6cf062203a94ef8404906d-7kYBGE_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f222659d251f9c30de6115145f5bd0e2b191e1fc58bbb_QrL9YU_fw658 {
            get {
                object obj = ResourceManager.GetObject("f222659d251f9c30de6115145f5bd0e2b191e1fc58bbb-QrL9YU_fw658", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap large_2uFt_7afe00001160125b {
            get {
                object obj = ResourceManager.GetObject("large_2uFt_7afe00001160125b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap login_bg {
            get {
                object obj = ResourceManager.GetObject("login_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 图片1 {
            get {
                object obj = ResourceManager.GetObject("图片1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 输入密码 {
            get {
                object obj = ResourceManager.GetObject("输入密码", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
